export const STYNX_AUTHZ_POLICY_EVALUATOR = Symbol('STYNX_AUTHZ_POLICY_EVALUATOR');
export const STYNX_AUTHZ_METADATA = Symbol('STYNX_AUTHZ_METADATA');
export const STYNX_AUTHZ_OPTIONS = Symbol('STYNX_AUTHZ_OPTIONS');
