export const STYNX_SESSIONS_OPTIONS = Symbol('STYNX_SESSIONS_OPTIONS');
export const STYNX_SESSION_STORE = Symbol('STYNX_SESSION_STORE');
export const STYNX_SESSION_MIRROR = Symbol('STYNX_SESSION_MIRROR');
