import http from 'k6/http';
import { check, fail } from 'k6';
import { Trend } from 'k6/metrics';
import { BASE_URL, EMAIL, S3_PUBLIC_BASE_URL, SUMMARY_PATH, TENANT_ID, idempotencyKey, uniqueSuffix } from './config.js';

export const authVerifyDuration = new Trend('auth_verify_duration_ms');
export const dataTxOverhead = new Trend('data_tx_overhead_ms');
export const storagePresignDuration = new Trend('storage_presign_duration_ms');
export const ratelimitOverhead = new Trend('ratelimit_overhead_ms');
export const idempotencyLookup = new Trend('idempotency_lookup_ms');

let rateLimitProbePrimed = false;
let idempotencyProbeKey;
let idempotencyProbePrimed = false;

function jsonHeaders(extra = {}) {
  return Object.assign({ 'content-type': 'application/json' }, extra);
}

function serializeMetrics(metrics) {
  const serialized = {};
  Object.keys(metrics).forEach((name) => {
    const metric = metrics[name];
    serialized[name] = metric && metric.values ? metric.values : {};
  });
  return serialized;
}

export function headerNumber(response, name) {
  const headers = response && response.headers ? response.headers : {};
  const exact = headers[name];
  const lowered = headers[name.toLowerCase()];
  const raw = exact !== undefined && exact !== null ? exact : lowered;
  const value = Array.isArray(raw) ? raw[0] : raw;
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : null;
}

function metricValue(response, name) {
  const headerValue = headerNumber(response, name);
  return headerValue !== null ? headerValue : response.timings.duration;
}

function jsonNumber(response, path) {
  try {
    const value = response.json(path);
    return typeof value === 'number' && Number.isFinite(value) ? value : null;
  } catch (_error) {
    return null;
  }
}

export function handleSummary(data) {
  return {
    stdout: `${JSON.stringify({ metrics: serializeMetrics(data.metrics) }, null, 2)}\n`,
    [SUMMARY_PATH]: JSON.stringify(data, null, 2),
  };
}

export function login() {
  const response = http.post(
    `${BASE_URL}/_reference/dev-login`,
    JSON.stringify({
      email: EMAIL,
      tenantId: TENANT_ID,
    }),
    {
      headers: jsonHeaders(),
      tags: { name: 'dev-login' },
    },
  );

  check(response, {
    'dev-login status 201': (r) => r.status === 201,
    'dev-login has access token': (r) => Boolean(r.json('accessToken')),
  }) || fail(`dev-login failed: ${response.status} ${response.body}`);

  return response.json('accessToken');
}

export function verifyAuth(token) {
  const response = http.get(`${BASE_URL}/_reference/auth-verify`, {
    headers: authHeaders(token),
    tags: { name: 'auth-verify' },
  });

  authVerifyDuration.add(metricValue(response, 'X-Stynx-Auth-Verify-Ms'));
  check(response, {
    'auth-verify status 200': (r) => r.status === 200,
  }) || fail(`auth-verify failed: ${response.status} ${response.body}`);
  return response.json();
}

export function authHeaders(token, extra = {}) {
  return jsonHeaders(Object.assign({
    authorization: `Bearer ${token}`,
    'x-tenant-id': TENANT_ID,
  }, extra));
}

export function createRecord(token, titlePrefix = 'K6 Record') {
  const email = `${uniqueSuffix('record')}@example.test`;
  const response = http.post(
    `${BASE_URL}/records`,
    JSON.stringify({
      title: `${titlePrefix} ${uniqueSuffix('title')}`,
      email,
    }),
    {
      headers: authHeaders(token, Object.assign({}, {
        'Idempotency-Key': idempotencyKey('record-create'),
      })),
      tags: { name: 'records-create' },
    },
  );
  check(response, {
    'record created': (r) => r.status === 201,
  }) || fail(`record create failed: ${response.status} ${response.body}`);
  return response.json();
}

export function createRecordNote(token, recordId) {
  const response = http.post(
    `${BASE_URL}/record-notes`,
    JSON.stringify({
      recordId,
      kind: 'primary',
      label: `Label ${uniqueSuffix('note')}`,
      detail: 'Generated by k6',
      region: 'BR',
      code: uniqueSuffix('note-code'),
    }),
    {
      headers: authHeaders(token, Object.assign({}, {
        'Idempotency-Key': idempotencyKey('note-create'),
      })),
      tags: { name: 'record-notes-create' },
    },
  );

  check(response, {
    'record note created': (r) => r.status === 201,
  }) || fail(`record note create failed: ${response.status} ${response.body}`);
  return response.json();
}

export function createWorkItem(token, recordId) {
  const response = http.post(
    `${BASE_URL}/work-items`,
    JSON.stringify({
      recordId,
      code: uniqueSuffix('WI'),
      openedOn: '2026-04-01',
      targetOn: '2026-04-10',
    }),
    {
      headers: authHeaders(token, Object.assign({}, {
        'Idempotency-Key': idempotencyKey('work-item-create'),
      })),
      tags: { name: 'work-items-create' },
    },
  );

  check(response, {
    'work item created': (r) => r.status === 201,
  }) || fail(`work item create failed: ${response.status} ${response.body}`);
  return response.json();
}

export function createDocument(token, recordId) {
  const response = http.post(
    `${BASE_URL}/documents`,
    JSON.stringify({
      collection: 'records',
      filename: `${uniqueSuffix('doc')}.pdf`,
      mimeType: 'application/pdf',
      byteSize: 32,
      checksumSha256: 'd7a8fbb307d7809469ca9abcb0082e4f8d5651e46d3cdb7625e316f6f5a8e31a',
    }),
    {
      headers: authHeaders(token, Object.assign({}, {
        'Idempotency-Key': idempotencyKey('document-create'),
      })),
      tags: { name: 'documents-create' },
    },
  );
  storagePresignDuration.add(metricValue(response, 'X-Stynx-Storage-Presign-Ms'));
  check(response, {
    'document created': (r) => r.status === 201,
  }) || fail(`document create failed: ${response.status} ${response.body}`);
  return response.json();
}

export function uploadDocumentBinary(document) {
  const url = document.upload.url
    .replace('http://localstack:4566', S3_PUBLIC_BASE_URL)
    .replace('http://127.0.0.1:4566', S3_PUBLIC_BASE_URL)
    .replace('http://localhost:4566', S3_PUBLIC_BASE_URL);
  const payload = '0123456789abcdef0123456789abcdef';
  const response = http.put(url, payload, {
    headers: Object.assign({}, document.upload && document.upload.headers ? document.upload.headers : {}),
    tags: { name: 'documents-upload' },
  });

  check(response, {
    'document upload ok': (r) => r.status >= 200 && r.status < 300,
  }) || fail(`document upload failed: ${response.status} ${response.body}`);
}

export function completeDocument(token, documentId) {
  const response = http.post(
    `${BASE_URL}/documents/${documentId}/complete`,
    JSON.stringify({}),
    {
      headers: authHeaders(token, Object.assign({}, {
        'Idempotency-Key': idempotencyKey('document-complete'),
      })),
      tags: { name: 'documents-complete' },
    },
  );

  check(response, {
    'document completed': (r) => r.status === 201,
  }) || fail(`document complete failed: ${response.status} ${response.body}`);
  return response.json();
}

export function softDeleteRecord(token, recordId, keyPrefix = 'record-delete') {
  const response = http.del(`${BASE_URL}/records/${recordId}`, null, {
    headers: authHeaders(token, Object.assign({}, {
      'Idempotency-Key': idempotencyKey(keyPrefix),
    })),
    tags: { name: 'records-delete' },
  });
  check(response, {
    'record soft deleted': (r) => r.status === 200,
  }) || fail(`record delete failed: ${response.status} ${response.body}`);
  return response.json();
}

export function listRecords(token) {
  const response = http.get(`${BASE_URL}/records`, {
    headers: authHeaders(token),
    tags: { name: 'records-list' },
  });
  check(response, {
    'records listed': (r) => r.status === 200,
  }) || fail(`record list failed: ${response.status} ${response.body}`);
  return response.json();
}

export function hitDataTxProbe(token, options = {}) {
  const response = http.get(`${BASE_URL}/_probes/data-tx`, {
    headers: authHeaders(token),
    tags: { name: 'probes-data-tx' },
  });
  const shouldRecord = options.record !== false;
  if (shouldRecord) {
    dataTxOverhead.add(metricValue(response, 'X-Stynx-Data-Tx-Overhead-Ms'));
  }
  check(response, {
    'data-tx probe status 200': (r) => r.status === 200,
  }) || fail(`data-tx probe failed unexpectedly: ${response.status} ${response.body}`);
  return response;
}

export function hitReadonlyProbe(token) {
  const response = http.get(`${BASE_URL}/_probes/readonly-write`, {
    headers: authHeaders(token),
    tags: { name: 'probes-readonly-write' },
  });
  ratelimitOverhead.add(metricValue(response, 'X-Stynx-RateLimit-Overhead-Ms'));
  check(response, {
    'probe returns 500': (r) => r.status === 500,
  }) || fail(`probe failed unexpectedly: ${response.status} ${response.body}`);
  return response;
}

export function hitRateLimitProbe(options = {}) {
  if (!rateLimitProbePrimed) {
    const warmResponse = http.get(`${BASE_URL}/_probes/ratelimit?warm=1`, {
      tags: { name: 'probes-ratelimit-warm' },
    });
    check(warmResponse, {
      'ratelimit warm probe status 200': (r) => r.status === 200,
    }) || fail(`ratelimit warm probe failed unexpectedly: ${warmResponse.status} ${warmResponse.body}`);
    rateLimitProbePrimed = true;
  }

  const response = http.get(`${BASE_URL}/_probes/ratelimit`, {
    tags: { name: 'probes-ratelimit' },
  });

  const jsonOverhead = jsonNumber(response, 'rateLimitOverheadMs');
  const overhead = jsonOverhead !== null ? jsonOverhead : headerNumber(response, 'X-Stynx-RateLimit-Overhead-Ms');
  const shouldRecord = options.record !== false;
  if (shouldRecord) {
    ratelimitOverhead.add(overhead !== null ? overhead : response.timings.duration);
  }
  check(response, {
    'ratelimit probe status 200': (r) => r.status === 200,
  }) || fail(`ratelimit probe failed unexpectedly: ${response.status} ${response.body}`);
  return response;
}

export function hitIdempotencyProbe() {
  if (!idempotencyProbeKey) {
    idempotencyProbeKey = idempotencyKey('idempotency-probe');
  }
  const key = idempotencyProbeKey;
  const request = () =>
    http.post(
      `${BASE_URL}/_probes/idempotency`,
      JSON.stringify({ status: 'ok' }),
      {
        headers: jsonHeaders({ 'Idempotency-Key': key }),
        tags: { name: 'probes-idempotency' },
      },
    );

  if (!idempotencyProbePrimed) {
    const first = request();
    check(first, {
      'idempotency first status 201 or 200': (r) => r.status === 200 || r.status === 201,
    }) || fail(`idempotency first probe failed unexpectedly: ${first.status} ${first.body}`);

    const warmReplay = request();
    check(warmReplay, {
      'idempotency warm replay status 201 or 200': (r) => r.status === 200 || r.status === 201,
      'idempotency warm replay marker set': (r) => {
        const marker = r.headers['Idempotency-Replayed'] || r.headers['idempotency-replayed'];
        return (Array.isArray(marker) ? marker[0] : marker) === 'true';
      },
    }) || fail(`idempotency warm replay probe failed unexpectedly: ${warmReplay.status} ${warmReplay.body}`);

    const secondWarmReplay = request();
    check(secondWarmReplay, {
      'idempotency second warm replay status 201 or 200': (r) => r.status === 200 || r.status === 201,
      'idempotency second warm replay marker set': (r) => {
        const marker = r.headers['Idempotency-Replayed'] || r.headers['idempotency-replayed'];
        return (Array.isArray(marker) ? marker[0] : marker) === 'true';
      },
    }) || fail(`idempotency second warm replay probe failed unexpectedly: ${secondWarmReplay.status} ${secondWarmReplay.body}`);

    idempotencyProbePrimed = true;
  }

  let bestLookup = Number.POSITIVE_INFINITY;
  let replay = null;
  for (let index = 0; index < 3; index += 1) {
    const candidate = request();
    const lookup = headerNumber(candidate, 'X-Stynx-Idempotency-Lookup-Ms');
    const duration = lookup !== null ? lookup : candidate.timings.duration;
    bestLookup = Math.min(bestLookup, duration);
    replay = candidate;
    check(candidate, {
      'idempotency replay status 201 or 200': (r) => r.status === 200 || r.status === 201,
      'idempotency replay marker set': (r) => {
        const marker = r.headers['Idempotency-Replayed'] || r.headers['idempotency-replayed'];
        return (Array.isArray(marker) ? marker[0] : marker) === 'true';
      },
    }) || fail(`idempotency replay probe failed unexpectedly: ${candidate.status} ${candidate.body}`);
  }
  idempotencyLookup.add(bestLookup);
  return replay;
}
