export const STYNX_OFFLINE_SYNC_OPTIONS = Symbol('STYNX_OFFLINE_SYNC_OPTIONS');
export const STYNX_OFFLINE_SYNC_STORE = Symbol('STYNX_OFFLINE_SYNC_STORE');
export const STYNX_OFFLINE_SYNC_CONTEXT = Symbol('STYNX_OFFLINE_SYNC_CONTEXT');
