version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      aws-sdk:
        patterns:
          - '@aws-sdk/*'
      nest:
        patterns:
          - '@nestjs/*'
      angular:
        patterns:
          - '@angular*'
          - '@angular-devkit/*'
      vitest:
        patterns:
          - 'vitest'
          - '@vitest/*'
          - 'unplugin-swc'
      dev:
        patterns:
          - '@changesets/*'
          - '@commitlint/*'
          - '@eslint/*'
          - '@types/*'
          - '@typescript-eslint/*'
          - 'eslint'
          - 'globals'
          - 'husky'
          - 'lint-staged'
          - 'prettier'
          - 'turbo'
          - 'typescript'

  - package-ecosystem: npm
    directory: /reference/web
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      angular:
        patterns:
          - '@angular*'
          - '@angular-devkit/*'
          - 'angular-oauth2-oidc'
      vitest:
        patterns:
          - 'vitest'
          - '@vitest/*'
      dev:
        patterns:
          - '@types/*'
          - '@typescript-eslint/*'
          - 'cross-env'
          - 'cypress'
          - 'eslint'
          - 'globals'
          - 'ts-*'
          - 'typescript'

  - package-ecosystem: npm
    directory: /reference/api
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      nest:
        patterns:
          - '@nestjs/*'
      vitest:
        patterns:
          - 'vitest'
          - '@vitest/*'
      dev:
        patterns:
          - '@types/*'
          - 'ts-*'
          - 'typescript'

  - package-ecosystem: npm
    directory: /test/db
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      vitest:
        patterns:
          - 'vitest'
          - '@vitest/*'
      dev:
        patterns:
          - '@types/*'
          - 'ts-*'
          - 'typescript'

  - package-ecosystem: npm
    directory: /test/packages
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      vitest:
        patterns:
          - 'vitest'
          - '@vitest/*'
      dev:
        patterns:
          - '@types/*'
          - 'ts-*'
          - 'typescript'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
