export const STYNX_IDEMPOTENCY_OPTIONS = Symbol('STYNX_IDEMPOTENCY_OPTIONS');
export const STYNX_IDEMPOTENCY_STORE = Symbol('STYNX_IDEMPOTENCY_STORE');
export const STYNX_IDEMPOTENCY_BACKEND = Symbol('STYNX_IDEMPOTENCY_BACKEND');
export const STYNX_IDEMPOTENCY_METRICS = Symbol('STYNX_IDEMPOTENCY_METRICS');
export const STYNX_IDEMPOTENT_ROUTE = Symbol('STYNX_IDEMPOTENT_ROUTE');
export const STYNX_NO_IDEMPOTENT_ROUTE = Symbol('STYNX_NO_IDEMPOTENT_ROUTE');
