const allowedScopes = [
  'stynx-workspace',
  '@stynx/reference-api',
  '@stynx/reference-web',
  '@stech/reference-frontend',
  '@stech/stynx-backend',
  '@stech/stynx-contracts',
  '@stech/stynx-frontend-client',
  '@stech/stynx-frontend-contracts',
  '@stynx/contracts',
  '@stynx/auth',
  '@stynx/audit',
  '@stynx/cli',
  '@stynx/core',
  '@stynx/data',
  '@stynx/i18n',
  '@stynx/privacy',
  '@stynx/ratelimit',
  '@stynx/idempotency',
  '@stynx/health',
  '@stynx/logging',
  '@stynx/sessions',
  '@stynx/storage',
  '@stynx/tenancy',
  '@stynx/testing',
  '@stynx-web/sdk',
  '@stynx-web/angular',
  '@stynx-web/angular-tenancy',
  '@stynx-web/angular-auth',
  '@stynx-web/angular-ui',
  '@stynx-web/angular-i18n',
  '@stynx-web/angular-trash',
  '@stynx-web/angular-storage',
  '@stynx-web/angular-sessions',
  '@stynx-web/angular-profile',
  '@stynx-internal/eslint-config',
  '@stynx-internal/tsconfig',
];

module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'scope-enum': [2, 'always', allowedScopes],
  },
};
