CREATE TABLE IF NOT EXISTS audit.log (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  occurred_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  table_schema text NOT NULL,
  table_name text NOT NULL,
  row_id text,
  operation text NOT NULL,
  tenant_id uuid,
  actor_id uuid,
  request_id text,
  session_id text,
  tags jsonb NOT NULL DEFAULT '{}'::jsonb,
  payload jsonb,
  PRIMARY KEY (occurred_at, id)
) PARTITION BY RANGE (occurred_at);

DO $$
DECLARE
  partition_start date := date_trunc('month', clock_timestamp())::date;
  partition_end date := (date_trunc('month', clock_timestamp()) + interval '1 month')::date;
  partition_name text := format('log_%s', to_char(partition_start, 'YYYY_MM'));
BEGIN
  EXECUTE format(
    'CREATE TABLE IF NOT EXISTS audit.%I PARTITION OF audit.log FOR VALUES FROM (%L) TO (%L)',
    partition_name,
    partition_start,
    partition_end
  );
END
$$;

CREATE TABLE IF NOT EXISTS audit.system_op (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  occurred_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  reason text NOT NULL,
  actor_id uuid,
  request_id text NOT NULL,
  payload jsonb
);

CREATE TABLE IF NOT EXISTS audit.disabled_tables (
  table_schema text NOT NULL,
  table_name text NOT NULL,
  reason text NOT NULL,
  disabled_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY (table_schema, table_name)
);

CREATE OR REPLACE FUNCTION audit.ensure_monthly_partition(reference_time timestamptz DEFAULT clock_timestamp())
RETURNS text
LANGUAGE plpgsql
AS $$
DECLARE
  partition_start date := date_trunc('month', reference_time)::date;
  partition_end date := (date_trunc('month', reference_time) + interval '1 month')::date;
  partition_name text := format('log_%s', to_char(partition_start, 'YYYY_MM'));
BEGIN
  EXECUTE format(
    'CREATE TABLE IF NOT EXISTS audit.%I PARTITION OF audit.log FOR VALUES FROM (%L) TO (%L)',
    partition_name,
    partition_start,
    partition_end
  );
  RETURN partition_name;
END
$$;

CREATE OR REPLACE FUNCTION audit.write(
  p_tenant_id uuid,
  p_actor_id uuid,
  p_actor_role text,
  p_operation text,
  p_entity text,
  p_entity_id text,
  p_metadata jsonb,
  p_ip_address text,
  p_session_id text,
  p_request_id text,
  p_old_data jsonb,
  p_new_data jsonb,
  p_pk jsonb
)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
  entity_schema text := split_part(COALESCE(p_entity, ''), '.', 1);
  entity_table text := split_part(COALESCE(p_entity, ''), '.', 2);
BEGIN
  PERFORM audit.ensure_monthly_partition(clock_timestamp());

  INSERT INTO audit.log (
    occurred_at,
    table_schema,
    table_name,
    row_id,
    operation,
    tenant_id,
    actor_id,
    request_id,
    session_id,
    tags,
    payload
  )
  VALUES (
    clock_timestamp(),
    NULLIF(CASE WHEN entity_table = '' THEN NULL ELSE entity_schema END, ''),
    COALESCE(NULLIF(entity_table, ''), NULLIF(entity_schema, ''), 'unknown'),
    p_entity_id,
    p_operation,
    p_tenant_id,
    p_actor_id,
    p_request_id,
    p_session_id,
    jsonb_strip_nulls(jsonb_build_object(
      'manual_event', true,
      'actor_role', p_actor_role
    )),
    jsonb_strip_nulls(jsonb_build_object(
      'metadata', COALESCE(p_metadata, '{}'::jsonb),
      'ip_address', p_ip_address,
      'pk', p_pk,
      'old', p_old_data,
      'new', p_new_data
    ))
  );
END
$$;

CREATE OR REPLACE FUNCTION audit.fn_row_change()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  archive_move text := NULLIF(current_setting('app.archive_move', true), '');
  archive_reason text := NULLIF(current_setting('app.archive_reason', true), '');
  erasure_strategy text := COALESCE(
    NULLIF(current_setting('app.erasure_strategy', true), ''),
    NULLIF(current_setting('app.lgpd_strategy', true), '')
  );
  current_tags jsonb := '{}'::jsonb;
  current_payload jsonb;
  current_row_id text := COALESCE(
    CASE WHEN TG_OP IN ('UPDATE', 'DELETE') THEN OLD.id::text ELSE NULL END,
    CASE WHEN TG_OP IN ('INSERT', 'UPDATE') THEN NEW.id::text ELSE NULL END
  );
  archive_table_name text := format('archive.%s_%s', TG_TABLE_SCHEMA, TG_TABLE_NAME);
BEGIN
  IF archive_move = 'in_progress'
     AND TG_TABLE_SCHEMA = 'archive'
     AND TG_OP = 'INSERT'
     AND archive_reason = 'soft_delete' THEN
    RETURN NEW;
  END IF;

  IF archive_move = 'in_progress'
     AND TG_TABLE_SCHEMA = 'archive'
     AND TG_OP = 'DELETE'
     AND archive_reason = 'restore' THEN
    RETURN NEW;
  END IF;

  IF archive_move = 'in_progress'
     AND TG_TABLE_SCHEMA <> 'archive'
     AND TG_OP = 'DELETE'
     AND archive_reason = 'soft_delete' THEN
    current_tags := jsonb_build_object(
      'soft_delete', true,
      'archived', true,
      'archive_table', archive_table_name
    );
  ELSIF archive_move = 'in_progress'
     AND TG_TABLE_SCHEMA <> 'archive'
     AND TG_OP = 'INSERT'
     AND archive_reason = 'restore' THEN
    current_tags := jsonb_build_object(
      'restore', true,
      'from_archive', true
    );
  ELSIF TG_TABLE_SCHEMA <> 'archive'
     AND TG_OP = 'DELETE' THEN
    current_tags := jsonb_build_object('hard_delete', true);
  ELSIF TG_TABLE_SCHEMA = 'archive'
     AND TG_OP = 'DELETE' THEN
    current_tags := jsonb_build_object('hard_delete', true, 'from_archive', true);
  ELSIF TG_TABLE_SCHEMA = 'archive'
     AND TG_OP = 'UPDATE'
     AND COALESCE(to_jsonb(NEW)->>'last_erasure_at', '')
       IS DISTINCT FROM COALESCE(to_jsonb(OLD)->>'last_erasure_at', '') THEN
    current_tags := jsonb_build_object(
      'lgpd_erasure', true,
      'strategy', COALESCE(erasure_strategy, 'unknown')
    );
  END IF;

  current_payload := jsonb_strip_nulls(
    jsonb_build_object(
      'archive_reason', archive_reason,
      'old', CASE WHEN TG_OP IN ('UPDATE', 'DELETE') THEN to_jsonb(OLD) ELSE NULL END,
      'new', CASE WHEN TG_OP IN ('INSERT', 'UPDATE') THEN to_jsonb(NEW) ELSE NULL END
    )
  );

  PERFORM audit.ensure_monthly_partition(clock_timestamp());

  INSERT INTO audit.log (
    occurred_at,
    table_schema,
    table_name,
    row_id,
    operation,
    tenant_id,
    actor_id,
    request_id,
    session_id,
    tags,
    payload
  )
  VALUES (
    clock_timestamp(),
    TG_TABLE_SCHEMA,
    TG_TABLE_NAME,
    current_row_id,
    TG_OP,
    NULLIF(current_setting('app.tenant_id', true), '')::uuid,
    NULLIF(current_setting('app.actor_id', true), '')::uuid,
    NULLIF(current_setting('app.request_id', true), ''),
    NULLIF(current_setting('app.session_id', true), ''),
    current_tags,
    current_payload
  );

  RETURN COALESCE(NEW, OLD);
END
$$;

CREATE OR REPLACE FUNCTION audit.enable_for(target_table regclass)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
  trigger_name text := format('trg_audit_%s', replace(target_table::text, '.', '_'));
BEGIN
  DELETE FROM audit.disabled_tables
  WHERE table_schema = split_part(target_table::text, '.', 1)
    AND table_name = split_part(target_table::text, '.', 2);

  EXECUTE format('DROP TRIGGER IF EXISTS %I ON %s', trigger_name, target_table);
  EXECUTE format(
    'CREATE TRIGGER %I AFTER INSERT OR UPDATE OR DELETE ON %s FOR EACH ROW EXECUTE FUNCTION audit.fn_row_change()',
    trigger_name,
    target_table
  );
END
$$;

CREATE OR REPLACE FUNCTION audit.disable_for(target_table regclass, disable_reason text)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
  trigger_name text := format('trg_audit_%s', replace(target_table::text, '.', '_'));
BEGIN
  EXECUTE format('DROP TRIGGER IF EXISTS %I ON %s', trigger_name, target_table);

  INSERT INTO audit.disabled_tables (table_schema, table_name, reason)
  VALUES (
    split_part(target_table::text, '.', 1),
    split_part(target_table::text, '.', 2),
    COALESCE(NULLIF(trim(disable_reason), ''), 'no reason provided')
  )
  ON CONFLICT (table_schema, table_name)
  DO UPDATE SET
    reason = EXCLUDED.reason,
    disabled_at = clock_timestamp();
END
$$;
