export const STYNX_RATE_LIMIT_OPTIONS = Symbol('STYNX_RATE_LIMIT_OPTIONS');
export const STYNX_RATE_LIMIT_STORE = Symbol('STYNX_RATE_LIMIT_STORE');
export const STYNX_RATE_LIMIT_POLICY = Symbol('STYNX_RATE_LIMIT_POLICY');
export const STYNX_RATE_LIMIT_METRICS = Symbol('STYNX_RATE_LIMIT_METRICS');
export const STYNX_RATE_LIMIT_ROUTE = Symbol('STYNX_RATE_LIMIT_ROUTE');
