import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

const pki = join(__dirname, 'pki');
export const bytes = (name: string): Uint8Array => readFileSync(join(pki, name));
export const hex = (value: Uint8Array): string => createHash('sha256').update(value).digest('hex');
export const rootPem = readFileSync(join(pki, 'root.cert.pem'), 'utf8');
export const signerPem = readFileSync(join(pki, 'signer.cert.pem'), 'utf8');
export const certificate = {
  subject: 'CN=STYNX Test Signer',
  issuer: 'CN=STYNX Test Trust Root',
  serialNumber: '1001',
  pem: signerPem,
};
export const sourceDocument = bytes('document.bin');
export const signedDocument = bytes('pades-signed.pdf');
export const cmsSignature = bytes('pades.cms.der');
// Generated by build-pades-blt.py: source is an exact signed ByteRange prefix.
export const bltSourceDocument = bytes('pades-source.pdf');
export const bltSignedDocument = bytes('pades-blt.pdf');
export const bltCmsSignature = bytes('pades-blt.cms.der');
export const bltTimestampResponse = bytes('pades-blt-timestamp.tsr');
export const now = new Date('2026-09-29T12:00:00.000Z');
export const profile = {
  id: 'clinical-test',
  revision: '1',
  environment: 'test',
  minimumSignatureLevel: 'ADVANCED',
  requiredPadesProfile: 'PAdES-B-LT',
  requireTsa: true,
  requireLta: false,
  revocation: 'ocsp-or-crl',
  trustAnchorsPem: [rootPem],
  acceptedPolicies: ['1.2.3.4.5.6.7'],
  atTime: 'trusted-timestamp',
} as const;
export const request = {
  tenantId: 'tenant-a',
  actorId: 'doctor-a',
  document: sourceDocument,
  documentSha256: hex(sourceDocument),
  tsa: { endpoint: 'https://tsa.example.test' },
  certificate,
  minimumSignatureLevel: 'ADVANCED',
  trustProfile: profile,
} as const;

// Second, disjoint test PKI (generate-root2.sh): nothing below chains to root.cert.pem.
// Used by the trust-profile-set proofs (ADR-SIGNATURE-0002 D2, UPS-SIG-07).
export const root2Pem = readFileSync(join(pki, 'root2.cert.pem'), 'utf8');
export const signer2Pem = readFileSync(join(pki, 'signer2.cert.pem'), 'utf8');
export const certificate2 = {
  subject: 'CN=STYNX Test Signer 2',
  issuer: 'CN=STYNX Test Trust Root 2',
  serialNumber: '2001',
  pem: signer2Pem,
};
export const blt2SourceDocument = bytes('pades-root2-source.pdf');
export const blt2SignedDocument = bytes('pades-root2-blt.pdf');
export const blt2CmsSignature = bytes('pades-root2-blt.cms.der');
// root2 fixtures were generated on 2026-10-09; every freshness rule is "not
// after now", so one later fixed instant is valid for both roots' artifacts.
export const now2 = new Date('2026-10-10T12:00:00.000Z');

export function signedResult(overrides: Record<string, unknown> = {}) {
  return {
    status: 'signed',
    signedDocument,
    cmsSignature,
    evidence: {
      signatureId: 'sig-1',
      documentSha256: hex(sourceDocument),
      signedAt: now,
      tsaTime: now,
      signerCertificate: certificate,
      revocationSource: 'ocsp',
      revocationCheckedAt: now,
    },
    ...overrides,
  };
}
