export const STYNX_SSE_CONTEXT_RUNNER = Symbol('STYNX_SSE_CONTEXT_RUNNER');
export const STYNX_SSE_SCHEDULER = Symbol('STYNX_SSE_SCHEDULER');
export const STYNX_SSE_METRICS = Symbol('STYNX_SSE_METRICS');
