export const STYNX_PREFERENCES_OPTIONS = Symbol('STYNX_PREFERENCES_OPTIONS');
export const STYNX_PREFERENCES_STORE = Symbol('STYNX_PREFERENCES_STORE');
export const STYNX_PREFERENCES_AUDIT = Symbol('STYNX_PREFERENCES_AUDIT');
export const STYNX_PREFERENCES_AVATAR = Symbol('STYNX_PREFERENCES_AVATAR');
