export const STYNX_OUTBOX_OPTIONS = Symbol('STYNX_OUTBOX_OPTIONS');
export const STYNX_OUTBOX_DISPATCHER = Symbol('STYNX_OUTBOX_DISPATCHER');
export const STYNX_OUTBOX_BACKOFF_POLICY = Symbol('STYNX_OUTBOX_BACKOFF_POLICY');
export const STYNX_OUTBOX_METRICS = Symbol('STYNX_OUTBOX_METRICS');

export const DEFAULT_OUTBOX_TABLE = 'outbox.messages';
export const DEFAULT_OUTBOX_ACK_TABLE = 'outbox.acknowledgements';
export const DEFAULT_OUTBOX_DISPATCH_BATCH_SIZE = 25;
