export const STYNX_SIGNATURE_OPTIONS = Symbol('STYNX_SIGNATURE_OPTIONS');
export const STYNX_SIGNATURE_BACKEND = Symbol('STYNX_SIGNATURE_BACKEND');
export const STYNX_SIGNATURE_PROVIDER_CLIENT = Symbol('STYNX_SIGNATURE_PROVIDER_CLIENT');
