export const STYNX_NOTIFICATIONS_OPTIONS = Symbol('STYNX_NOTIFICATIONS_OPTIONS');
export const STYNX_NOTIFICATIONS_PREFERENCES_PORT = Symbol('STYNX_NOTIFICATIONS_PREFERENCES_PORT');
export const STYNX_NOTIFICATIONS_TEMPLATE_REGISTRY = Symbol(
  'STYNX_NOTIFICATIONS_TEMPLATE_REGISTRY',
);
export const STYNX_NOTIFICATIONS_CHANNEL_ADAPTERS = Symbol(
  'STYNX_NOTIFICATIONS_CHANNEL_ADAPTERS',
);
