const allowedScopes = [
  'stynx-workspace',
  '@stynx/reference-api',
  '@stynx/reference-web',
  '@stynx/backend',
  '@stynx/contracts',
  '@stynx/auth',
  '@stynx/audit',
  '@stynx/cli',
  '@stynx/core',
  '@stynx/data',
  '@stynx/i18n',
  '@stynx/privacy',
  '@stynx/ratelimit',
  '@stynx/idempotency',
  '@stynx/health',
  '@stynx/logging',
  '@stynx/sessions',
  '@stynx/storage',
  '@stynx/tenancy',
  '@stynx/testing',
  '@stynx-web/angular',
  '@stynx-web/angular-tenancy',
  '@stynx-web/angular-auth',
  '@stynx-web/angular-ui',
  '@stynx-web/angular-i18n',
  '@stynx-web/angular-trash',
  '@stynx-web/angular-storage',
  '@stynx-web/angular-sessions',
  '@stynx-web/angular-profile',
  '@stynx-internal/eslint-config',
  '@stynx-internal/tsconfig',
  '@stynx-internal/migration-linter',
  'clean',
  'deps',
  'deps-dev',
  'repo',
];

module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'header-max-length': [2, 'always', 100],
    'scope-enum': [2, 'always', allowedScopes],
    'subject-case': [2, 'never', ['sentence-case', 'start-case', 'pascal-case', 'upper-case']],
    'type-enum': [
      2,
      'always',
      [
        'build',
        'chore',
        'ci',
        'docs',
        'feat',
        'fix',
        'perf',
        'refactor',
        'revert',
        'style',
        'test',
      ],
    ],
  },
};
