export const STYNX_AUDIT_SINK = Symbol('STYNX_AUDIT_SINK');
export const STYNX_AUDIT_METADATA = Symbol('STYNX_AUDIT_METADATA');
export const STYNX_AUDIT_METADATA_REDACTION_POLICY = Symbol(
  'STYNX_AUDIT_METADATA_REDACTION_POLICY',
);
