import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

function write(filePath: string, content: string): void {
  mkdirSync(resolve(filePath, '..'), { recursive: true });
  writeFileSync(filePath, content, 'utf8');
}

export function scaffoldApp(targetDir: string, appName: string, angular = false): void {
  mkdirSync(targetDir, { recursive: true });
  write(resolve(targetDir, 'package.json'), JSON.stringify({
    name: appName,
    private: true,
    scripts: {
      build: 'tsc -p tsconfig.json',
      test: 'node --test',
    },
    dependencies: {
      '@stynx/core': 'workspace:*',
      '@stynx/data': 'workspace:*',
      '@stynx/auth': 'workspace:*',
      '@stynx/sessions': 'workspace:*',
      '@stynx/storage': 'workspace:*',
      '@stynx/privacy': 'workspace:*',
      '@stynx/i18n': 'workspace:*',
    },
  }, null, 2) + '\n');
  write(resolve(targetDir, 'tsconfig.json'), JSON.stringify({
    extends: '../../tools/tsconfig/node24.json',
    compilerOptions: { outDir: 'dist' },
    include: ['src/**/*.ts'],
  }, null, 2) + '\n');
  write(resolve(targetDir, 'src/main.ts'), "export function main() { return 'stynx-app'; }\n");
  write(resolve(targetDir, 'README.md'), `# ${appName}\n\nGenerated by stynx init.\n`);
  write(resolve(targetDir, 'Dockerfile'), 'FROM node:24-alpine\nWORKDIR /app\nCOPY . .\n');
  write(
    resolve(targetDir, 'docker-compose.yml'),
    "services:\n  postgres:\n    image: postgres:16-alpine\n    environment:\n      GLOG_minloglevel: '2'\n",
  );
  write(resolve(targetDir, '.env.example'), 'DATABASE_URL=postgresql://postgres:postgres@localhost:5432/postgres\n');
  write(resolve(targetDir, 'CODEOWNERS'), '* @platform-team\n');
  write(resolve(targetDir, 'infra/README.md'), '# Infra\n\nCDK skeleton placeholder.\n');
  write(resolve(targetDir, 'migrations/0001_init.sql'), "select data.create_soft_deletable_table($$\nCREATE TABLE app.records (\n  id uuid primary key,\n  tenant_id uuid not null,\n  name text not null\n)\n$$);\n");
  write(resolve(targetDir, 'app/privacy/pii-map.yaml'), 'rules: []\n');
  if (angular) {
    write(resolve(targetDir, 'angular.json'), JSON.stringify({ version: 1, projects: {} }, null, 2) + '\n');
  }
}
