export const STYNX_SESSION_CONTROL_OPTIONS = Symbol('STYNX_SESSION_CONTROL_OPTIONS');
export const STYNX_SESSION_REGISTRY = Symbol('STYNX_SESSION_REGISTRY');
export const STYNX_SESSION_PROVIDER = Symbol('STYNX_SESSION_PROVIDER');
export const STYNX_SESSION_CONTROL_AUDIT = Symbol('STYNX_SESSION_CONTROL_AUDIT');
