export const STYNX_PRIVACY_OPTIONS = Symbol('STYNX_PRIVACY_OPTIONS');
export const STYNX_PRIVACY_OBJECT_STORE = Symbol('STYNX_PRIVACY_OBJECT_STORE');
export const STYNX_PRIVACY_COGNITO_ADMIN = Symbol('STYNX_PRIVACY_COGNITO_ADMIN');
