export const STYNX_TOKEN_VERIFIER = Symbol('STYNX_TOKEN_VERIFIER');
export const STYNX_PRINCIPAL_MAPPER = Symbol('STYNX_PRINCIPAL_MAPPER');
export const STYNX_TENANT_RESOLVER = Symbol('STYNX_TENANT_RESOLVER');
export const STYNX_TENANT_ENTITLEMENT_POLICY = Symbol('STYNX_TENANT_ENTITLEMENT_POLICY');
