-- Generated from BP-DEMO-BOOKMARK-001 v0.1.0 sha256:a5553692
-- Generated by machine for demo/Bookmark
-- spec: 0.1.0 sha: a5553692

create schema if not exists demo;

-- enums
-- example: create type demo.__enum_name__ as enum ('A','B');

-- table for entity Bookmark
create table if not exists demo.demo__bookmark_bookmark (
  id uuid primary key default gen_random_uuid(),
  -- add fields below (scaffolder expands from spec)
  created_at timestamptz not null default now()
);

-- indexes (example)
-- create index if not exists ix_demo__bookmark_bookmark__field on demo.demo__bookmark_bookmark (__field);

