export const STYNX_SLA_OPTIONS = Symbol('STYNX_SLA_OPTIONS');
export const STYNX_SLA_EVENT_SINK = Symbol('STYNX_SLA_EVENT_SINK');
export const STYNX_SLA_CATEGORY_RESOLVER = Symbol('STYNX_SLA_CATEGORY_RESOLVER');
