export const STYNX_DB_CONTEXT_APPLIER = Symbol('STYNX_DB_CONTEXT_APPLIER');
export const STYNX_DB_CLIENT_RESOLVER = Symbol('STYNX_DB_CLIENT_RESOLVER');
export const STYNX_REQUEST_DB_CLIENT_LIFECYCLE = Symbol(
  'STYNX_REQUEST_DB_CLIENT_LIFECYCLE',
);
